### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Eyeball-Kun** [AlexProgrammerDE/ServerWrecker#55]
`XXXX@XXXXX:~/mcddoss/ServerWrecker/core/build/libs$ java -jar serverwrecker-core-all.jar 
00:31:49.014 INFO [org.pf4j.DefaultPluginStatusProvider] Enabled plugins: []
00:31:49.016 INFO [org.pf4j.DefaultPluginStatusProvider] Disabled plugins: []
00:31:49.018 INFO [org.pf4j.DefaultPluginManager] PF4J version 3.7.0 in 'deployment' mode
00:31:49.021 INFO [org.pf4j.AbstractPluginManager] No plugins
00:31:49.029 ERROR [ServerWrecker] Can't load library: /usr/lib/jvm/java-17-openjdk-amd64/lib/libawt_xawt.so
java.lang.UnsatisfiedLinkError: Can't load library: /usr/lib/jvm/java-17-openjdk-amd64/lib/libawt_xawt.so
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2393)
	at java.base/java.lang.Runtime.load0(Runtime.java:755)
	at java.base/java.lang.System.load(System.java:1953)
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
	at java.base/jdk.internal.loader.NativeLibraries.findFromPaths(NativeLibraries.java:315)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:285)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2398)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)
	at java.base/java.lang.System.loadLibrary(System.java:1989)
	at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:1392)
	at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:1390)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at java.desktop/java.awt.Toolkit.loadLibraries(Toolkit.java:1389)
	at java.desktop/java.awt.Toolkit.initStatic(Toolkit.java:1427)
	at java.desktop/java.awt.Toolkit.<clinit>(Toolkit.java:1401)
	at java.desktop/java.awt.Component.<clinit>(Component.java:624)
	at net.pistonmaster.serverwrecker.Main.main(Main.java:40)
`
im VERY new to java and dont know how it works. I tried rebuilding it and i cant seem to get it to work.

**Comment by Eyeball-Kun** [comment]
fixed the issue, had wrong version of java.
